name: Build BeatportDL for Windows

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-taglib
            mingw-w64-x86_64-zlib

      - name: Build windows-amd64
        shell: msys2 {0}
        run: |
          export WINDOWS_AMD64_LIB_PATH="-L/mingw64/lib -I/mingw64/include"
          make windows-amd64
          ls -lah bin

      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: beatportdl-windows-amd64
          path: bin/beatportdl-windows-amd64.exe
